run:
  skip-dirs:
  - it
  timeout: 10m
  tests: true

linters:
  disable-all: true
  enable:
  # Default
  - deadcode
  - errcheck
  - gosimple
  - govet
  - ineffassign
  - staticcheck
  - structcheck
  - typecheck
  - unused
  - varcheck

  # Additionally linters
  - containedctx
  - decorder
  - errname
  - gosec
  - ireturn
  - makezero
  - misspell
  - unparam
  - whitespace
  - wrapcheck

linters-settings:
  # https://golangci-lint.run/usage/linters/#ireturn
  ireturn:
    allow:
    - anon
    - error
    - empty
    - stdlib
    - github.com\/dedalus-cis4u\/proxy\/t1k\/test\/scheme\.Database
