package flags

const (
	DRONE_BUILD_CREATED        string = "drone-build-created"
	DRONE_BUILD_EVENT          string = "drone-build-event"
	DRONE_BUILD_FINISHED       string = "drone-build-finished"
	DRONE_BUILD_LINK           string = "drone-build-link"
	DRONE_BUILD_NUMBER         string = "drone-build-number"
	DRONE_BUILD_STARTED        string = "drone-build-started"
	DRONE_BUILD_STATUS         string = "drone-build-status"
	DRONE_COMMIT_AUTHOR_NAME   string = "drone-commit-author-name"
	DRONE_COMMIT_AUTHOR_AVATAR string = "drone-commit-author-avatar"
	DRONE_COMMIT_AUTHOR_EMAIL  string = "drone-commit-author-email"
	DRONE_COMMIT_BRANCH        string = "drone-commit-branch"
	DRONE_COMMIT_LINK          string = "drone-commit-link"
	DRONE_COMMIT_MESSAGE       string = "drone-commit-message"
	DRONE_COMMIT_REF           string = "drone-commit-ref"
	DRONE_COMMIT_SHA           string = "drone-commit-sha"
	DRONE_DEPLOY_TO            string = "drone-deploy-to"
	DRONE_JOB_EXIT_CODE        string = "drone-job-exit-code"
	DRONE_JOB_FINISHED         string = "drone-job-finished"
	DRONE_JOB_NUMBER           string = "drone-job-number"
	DRONE_JOB_STARTED          string = "drone-job-started"
	DRONE_JOB_STATUS           string = "drone-job-status"
	DRONE_PREV_BUILD_NUMBER    string = "drone-prev-build-number"
	DRONE_PREV_BUILD_STATUS    string = "drone-prev-build-status"
	DRONE_PREV_COMMIT_SHA      string = "drone-prev-commit-sha"
	DRONE_PULL_REQUEST         string = "drone-pull-request"
	DRONE_REMOTE_URL           string = "drone-remote-url"
	DRONE_REPO                 string = "drone-repo"
	DRONE_REPO_AVATAR          string = "drone-repo-avatar"
	DRONE_REPO_BRANCH          string = "drone-repo-branch"
	DRONE_REPO_LINK            string = "drone-repo-link"
	DRONE_REPO_NAME            string = "drone-repo-name"
	DRONE_REPO_OWNER           string = "drone-repo-owner"
	DRONE_REPO_PRIVATE         string = "drone-repo-private"
	DRONE_REPO_SCM             string = "drone-repo-scm"
	DRONE_REPO_TRUSTED         string = "drone-repo-trusted"
	DRONE_TAG                  string = "drone-tag"
	DRONE_YAML_SIGNED          string = "drone-yaml-signed"
	DRONE_YAML_VERIFIED        string = "drone-yaml-verified"
)

const (
	SMTP_FROM_ADDRESS             string = "smtp-from-address"
	SMTP_FROM_NAME                string = "smtp-from-name"
	SMTP_HELO                     string = "smtp-helo"
	SMTP_HOST                     string = "smtp-host"
	SMTP_MAIL_SUBJECT             string = "smtp-mail-subject"
	SMTP_PASSWORD                 string = "smtp-password"
	SMTP_PORT                     string = "smtp-port"
	SMTP_START_TLS                string = "smtp-no-start-tls"
	SMTP_TLS_INSECURE_SKIP_VERIFY string = "smtp-tls-insecure"
	SMTP_TO_ADDRESSES             string = "smtp-to-addresses"
	SMTP_USERNAME                 string = "smtp-username"
)
